version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.intellij
    versions:
    - 0.7.0
    - 0.7.2
  - dependency-name: org.jetbrains.grammarkit
    versions:
    - 2020.3.2
